name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: npm install, build and test
      run: |
        cd ./frontend/
        npm install 
        npm build
    - name: Build the Docker image
      run: docker build . --file ./docker/Dockerfile 
    - name: Push 
      run: docker push -t zozk/nginx-proxy-manager
